baseURL = 'https://gautamiyer.com/'
languageCode = 'en-us'
title = 'Gautam Iyer'

[params]
  description = "Writer and researcher interested in cities, urban policy, and the built environment."
  author = "Gautam Iyer"
